package com.agent.common.dto;

import java.util.List;

import lombok.Data;

/**
 * DTO for chat responses from the AI agent.
 */
@Data
public class ChatResponse {

    /** The answer generated by the AI agent */
    private String answer;

    /** Session identifier for conversation continuity */
    private String sessionId;

    /** List of tool names that were used during response generation */
    private List<String> toolsUsed;

    /** List of source documents used for RAG-based answers */
    private List<SourceDTO> sources;
}
